# **NUMPY**

1. How to extract all odd numbers from arr?

In [ ]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr=arr[arr%2==1]
arr

array([1, 3, 5, 7, 9])

2. Replace all odd numbers in arr with -1 without changing

In [ ]:
import numpy as np
arr=np.array([0,1,2,3,4,5,6,7,8,9])
arr[np.where(arr%2==1)]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

3. Convert a 1D array to a 2D array with 2 rows

In [ ]:
import numpy as np
arr=np.array([0,1,2,3,4,5,6,7,8,9])
newarr=arr.reshape(2,5)
print(newarr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


4.Stack arrays a and b vertically

In [ ]:
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

c=np.vstack((a,b))
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


5. Stack the arrays a and b horizontally.

In [ ]:
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
c=np.hstack((a,b))
print(c)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


6.How to get the common items between two python numpy arrays?

In [ ]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c=np.intersect1d(a,b)
print(c)

[2 4]


7.How to remove from one array those items that exist in another?

In [ ]:
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
c=np.setdiff1d(a,b)
c

array([1, 2, 3, 4])

8. How to get the positions where elements of two arrays match?

In [ ]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c=np.where(a==b)
c

(array([1, 3, 5, 7]),)

9. How to extract all numbers between a given range from a numpy array?Get all items between 5 and 10 from a

In [ ]:
import numpy as np

ini_array = np.array([1, 2, 3, 45, 4, 7, 810, 9, 6])
result = np.where(np.logical_and(ini_array >= 6, ini_array <= 10))
print("Resultant array:", result)

Resultant array: (array([5, 7, 8]),)


# ***PANDAS***

***Pandas Data Series***

1. Write a Pandas program to convert a dictionary to a Pandas series.

In [ ]:
import pandas as pd
d={'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
s=pd.Series(d)
s

a    100
b    200
c    300
d    400
e    800
dtype: int64

2. Write a Pandas program to convert a NumPy array to a Pandas series.

In [ ]:
import pandas as pd
a=[10,20,30,40,50]
myvar = pd.Series(a)
myvar


0    10
1    20
2    30
3    40
4    50
dtype: int64

3. Write a Pandas program to change the data type of given a column or a Series.

In [ ]:
import pandas as pd
s1=pd.Series(["100","200","python","300.12","400" ])
print("orginal series:")
print(s1)
s2=pd.to_numeric(s1,errors='coerce')
print("new series:")
print(s2)


orginal series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
new series:
0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64


4. Write a Pandas program to convert the first column of a DataFrame as a Series.

In [ ]:
import pandas as pd
data={"col1":[1,2,3,4,7,11],
      "col2":[4,5,6,9,5,0],
      "col3":[7,5,8,12,1,11]}
df=pd.DataFrame(data,index=["a","b","c","d","e","f"])
print("dataframe:")
print(df)
s=df["col1"]
print("first column of df:")
print(s)
print("type of 1st column:")
type(s)

dataframe:
   col1  col2  col3
a     1     4     7
b     2     5     5
c     3     6     8
d     4     9    12
e     7     5     1
f    11     0    11
first column of df:
a     1
b     2
c     3
d     4
e     7
f    11
Name: col1, dtype: int64
type of 1st column:


pandas.core.series.Series

5. Write a Pandas program to convert a given Series to an array.

In [ ]:
import pandas as pd
import numpy as np

s=[1, 2, 5, 6, 9, 12, 15]
# Define a Pandas Series
x = pd.Series(s)

# Convert the Series to a NumPy array
new_array = x.to_numpy()

# View the NumPy array
new_array

array([ 1,  2,  5,  6,  9, 12, 15])

6 Write a Pandas program to convert Series of lists to one Series

In [ ]:
import pandas as pd
s1=pd.Series([["red","green","white"],["red","black"],["yellow"]])
print("orginal series")
print(s1)
s2=s1.explode().reset_index(drop=True)
print(s2)

orginal series
0    [red, green, white]
1           [red, black]
2               [yellow]
dtype: object
0       red
1     green
2     white
3       red
4     black
5    yellow
dtype: object


7.Write a Pandas program to sort a given Series.

In [ ]:
import pandas as pd
s1=pd.Series(["100","200","python","300.12","400" ])
print("orginal series:")
print(s1)
s2=s1.sort_values(ascending=True)
print(s2)

orginal series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
0       100
1       200
3    300.12
4       400
2    python
dtype: object


# ***Pandas DataFrame***

1.Write a Pandas program to create a dataframe from a dictionary and display it.

In [ ]:
import pandas as pd

data={'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}
df=pd.DataFrame(data)
df

X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83

2. Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels.

In [ ]:
import pandas as pd

data = {'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'],'score': [12.5, 9, 16.5, "np.nan", 9, 20, 14.5, "np.nan", 8, 19]}
df=pd.DataFrame(data,index= ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
df

attempts       name qualify   score
a         1  Anastasia     yes    12.5
b         3       Dima      no       9
c         2  Katherine     yes    16.5
d         3      James      no  np.nan
e         2      Emily      no       9
f         3    Michael     yes      20
g         1    Matthew     yes    14.5
h         1      Laura      no  np.nan
i         2      Kevin      no       8
j         1      Jonas     yes      19

3. Write a Pandas program to get the first 3 rows of a given DataFrame.

In [ ]:
import pandas as pd
data = {'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'],'score': [12.5, 9, 16.5, "np.nan", 9, 20, 14.5, "np.nan", 8, 19]}
df=pd.DataFrame(data,index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
print(df.loc[['a','b','c']])

   attempts       name qualify score
a         1  Anastasia     yes  12.5
b         3       Dima      no     9
c         2  Katherine     yes  16.5


4.Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

In [ ]:
import pandas as pd
data = {'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'],'score': [12.5, 9, 16.5, "np.nan", 9, 20, 14.5, "np.nan", 8, 19]}
df=pd.DataFrame(data,index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
print(df[["name","score"]])

        name   score
a  Anastasia    12.5
b       Dima       9
c  Katherine    16.5
d      James  np.nan
e      Emily       9
f    Michael      20
g    Matthew    14.5
h      Laura  np.nan
i      Kevin       8
j      Jonas      19


5. Write a Pandas program to select the specified columns and rows from a given data frame.Select 'name' and 'score' columns in rows 1, 3, 5, 6 from the following data frame.

In [ ]:
import pandas as pd
data = {'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'],'score': [12.5, 9, 16.5, "np.nan", 9, 20, 14.5, "np.nan", 8, 19]}
df=pd.DataFrame(data,index= [1,2,3,4,5,6,7,8,9,10])
print(df.loc[[1,3,5,6],["name","score"]])

        name score
1  Anastasia  12.5
3  Katherine  16.5
5      Emily     9
6    Michael    20


6. Write a Pandas program to select the rows where the number of attempts in the examination is greater than 2.

In [ ]:
import pandas as pd
data = {'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'],'score': [12.5, 9, 16.5, "np.nan", 9, 20, 14.5, "np.nan", 8, 19]}
df=pd.DataFrame(data,index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
print(df[df["attempts"]>2])


   attempts     name qualify   score
b         3     Dima      no       9
d         3    James      no  np.nan
f         3  Michael     yes      20


7. Write a Pandas program to select the rows where the score is missing, i.e. is NaN.

In [ ]:
import pandas as pd

exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data, index=labels)

missing_scores = df[df['score'].isnull()]

print("Rows where score is missing:")
print(missing_scores)

Rows where score is missing:
    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no


8. Write a Pandas program to select the rows the score is between 15 and 20 (inclusive).

In [ ]:
import pandas as pd

exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data, index=labels)
newdf = df[df['score'].between(15, 20)]
print(newdf)

        name  score  attempts qualify
c  Katherine   16.5         2     yes
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes


9. Write a Pandas program to select the rows where number of attempts in the examination is less than 2 and score greater than 15.

In [1]:
import pandas as pd


data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David'],
    'attempts': [1, 3, 1, 2],
    'score': [20, 10, 25, 18]
}
df = pd.DataFrame(data)
filtered_df = df[(df['attempts'] < 2) & (df['score'] > 15)]
print(filtered_df)

      name  attempts  score
0    Alice         1     20
2  Charlie         1     25


10. Write a Pandas program to change the score in row 'd' to 11.5.

In [ ]:
import pandas as pd

exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data, index=labels)
print("orginal dataframe")
print(df)
df.loc['d','score']=11.5
print("after update")
print(df)

orginal dataframe
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
after update
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


11. Write a Pandas program to calculate the sum of the examination attempts by the students.

In [ ]:
import pandas as pd

exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data, index=labels)
sum=df['attempts'].sum()
print("Sum of the examination attempts by the students:")
print(sum)

Sum of the examination attempts by the students:
19


12.Write a Pandas program to calculate the mean of all students' scores. Data is stored in a dataframe.

In [ ]:
import pandas as pd

exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data, index=labels)
m=df['score'].mean()
print("Sum of the examination attempts by the students:")
print(m)

Sum of the examination attempts by the students:
13.5625


13.Write a Pandas program to replace the 'qualify' column contains the values 'yes' and 'no' with True and False.

In [ ]:
import pandas as pd

exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data, index=labels)
print(df)
df['qualify']=df['qualify'].map({'yes':True,'no':False})
print("update DataFrame")
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
update DataFrame
        name  score  attempts  qualify
a  Anastasia   12.5         1     True
b       Dima    9.0         3    False
c  Katherine   16.5         2     True
d      James    NaN         3    False
e      Emily    9.0         2    False
f    Michael   20.0         3     True
g    Matthew   14.5         1     True
h      Laura    NaN         1    False
i      Kevin    8.0         2    False
j      Jonas   19.0         1     True


14.Write a Pandas program to change the name 'James' to 'Suresh' in name column of the DataFrame.

In [ ]:

import pandas as pd

exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data, index=labels)
print(df)
#df.loc["d","name"]="Suresh"
print("\nUpdated:")
df['name']=df['name'].replace('James','suresh')
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

Updated:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d     suresh    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


15. Write a Pandas program to delete the 'attempts' column from the DataFrame.

In [ ]:
import pandas as pd

exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, "np.nan", 9, 20, 14.5, "np.nan", 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data, index=labels)
print(df)
df.pop('attempts')
print(df)

        name   score  attempts qualify
a  Anastasia    12.5         1     yes
b       Dima       9         3      no
c  Katherine    16.5         2     yes
d      James  np.nan         3      no
e      Emily       9         2      no
f    Michael      20         3     yes
g    Matthew    14.5         1     yes
h      Laura  np.nan         1      no
i      Kevin       8         2      no
j      Jonas      19         1     yes
        name   score qualify
a  Anastasia    12.5     yes
b       Dima       9      no
c  Katherine    16.5     yes
d      James  np.nan      no
e      Emily       9      no
f    Michael      20     yes
g    Matthew    14.5     yes
h      Laura  np.nan      no
i      Kevin       8      no
j      Jonas      19     yes


16. Write a Pandas program to insert a new column in existing DataFrame.

In [ ]:
import pandas as pd
data = {'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'],
        'score': [12.5, 9, 16.5, "np.nan", 9, 20, 14.5, "np.nan", 8, 19]}
df=pd.DataFrame(data,index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
print("orginal dataframe:")
print(df)
df["color"]=['Red','Green','white','blue','yellow','violet','indigo','orange','black','pink']
print("\nafter  adding column:")
df

orginal dataframe:
   attempts       name qualify   score
a         1  Anastasia     yes    12.5
b         3       Dima      no       9
c         2  Katherine     yes    16.5
d         3      James      no  np.nan
e         2      Emily      no       9
f         3    Michael     yes      20
g         1    Matthew     yes    14.5
h         1      Laura      no  np.nan
i         2      Kevin      no       8
j         1      Jonas     yes      19

after  adding column:


attempts       name qualify   score   color
a         1  Anastasia     yes    12.5     Red
b         3       Dima      no       9   Green
c         2  Katherine     yes    16.5   white
d         3      James      no  np.nan    blue
e         2      Emily      no       9  yellow
f         3    Michael     yes      20  violet
g         1    Matthew     yes    14.5  indigo
h         1      Laura      no  np.nan  orange
i         2      Kevin      no       8   black
j         1      Jonas     yes      19    pink

17. Write a Pandas program to rename columns of a given DataFrame

In [ ]:
import pandas as pd
data={"col1":[1,2,3],
      "col2":[4,5,6],
      "col3":[7,8,9]}
df=pd.DataFrame(data)
print("orginal dataframe:")
print(df)
newdf=df.rename(columns={'col1':'column1','col2':'column2','col3':'column3'})
print("\nNew DataFrame after renaming columns:")
print(newdf)

orginal dataframe:
   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6     9

New DataFrame after renaming columns:
   column1  column2  column3
0        1        4        7
1        2        5        8
2        3        6        9


18. Write a Pandas program to select rows from a given DataFrame based on values in some columns.

In [ ]:
import pandas as pd
data={"col1":[1,4,3,4,5],
      "col2":[4,5,6,7,8],
      "col3":[7,8,9,0,1]}
df=pd.DataFrame(data)
print("orginal dataframe:")
print(df)
newdf=df.loc[df['col1']==4]
print("\nRows for colum1 value == 4")
print(newdf)

orginal dataframe:
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1

Rows for colum1 value == 4
   col1  col2  col3
1     4     5     8
3     4     7     0


19. Write a Pandas program to add one row in an existing DataFrame.

In [ ]:
import pandas as pd
data={"col1":[1,4,3,4,5],
      "col2":[4,5,6,7,8],
      "col3":[7,8,9,0,1]}
df=pd.DataFrame(data)
print("orginal dataframe:")
print(df)
df.loc[len(df.index)]=[10,11,12]
print("\nAfter add one row:")
print(df)

orginal dataframe:
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1

After add one row:
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1
5    10    11    12


20.Write a Pandas program to replace all the NaN values with Zero's in a column of a dataframe.



In [ ]:
import pandas as pd
data = {'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'],
        'score': [12.5, 9, 16.5, "np.nan", 9, 20, 14.5, "np.nan", 8, 19]}
df=pd.DataFrame(data,index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
print("orginal dataframe:")
print(df)
df['score'] =df['score'].replace("np.nan", 0)
print("\nAfter eliminate the NaN value:")
print(df)

orginal dataframe:
   attempts       name qualify   score
a         1  Anastasia     yes    12.5
b         3       Dima      no       9
c         2  Katherine     yes    16.5
d         3      James      no  np.nan
e         2      Emily      no       9
f         3    Michael     yes      20
g         1    Matthew     yes    14.5
h         1      Laura      no  np.nan
i         2      Kevin      no       8
j         1      Jonas     yes      19

After eliminate the NaN value:
   attempts       name qualify  score
a         1  Anastasia     yes   12.5
b         3       Dima      no    9.0
c         2  Katherine     yes   16.5
d         3      James      no    0.0
e         2      Emily      no    9.0
f         3    Michael     yes   20.0
g         1    Matthew     yes   14.5
h         1      Laura      no    0.0
i         2      Kevin      no    8.0
j         1      Jonas     yes   19.0


21.Write a Pandas program to count the NaN values in one or more columns in DataFrame.

In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
df = pd.DataFrame(exam_data)
print("Original DataFrame")
print(df)
print("\nNumber of NaN values in one or more columns:")
print(df.isnull().values.sum())

Original DataFrame
        name  score  attempts qualify
0  Anastasia   12.5         1     yes
1       Dima    9.0         3      no
2  Katherine   16.5         2     yes
3      James    NaN         3      no
4      Emily    9.0         2      no
5    Michael   20.0         3     yes
6    Matthew   14.5         1     yes
7      Laura    NaN         1      no
8      Kevin    8.0         2      no
9      Jonas   19.0         1     yes

Number of NaN values in one or more columns:
2


22.Write a Pandas program to drop a list of rows from a specified DataFrame.

In [ ]:
import pandas as pd
data={"col1":[1,4,3,4,5],
      "col2":[4,5,6,7,8],
      "col3":[7,8,9,0,1]}
df=pd.DataFrame(data)
print("orginal dataframe:")
print(df)
print("\nNew DataFrame after removing 2nd & 4th rows:")
df=df.drop([2,4])
print(df)

orginal dataframe:
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1

New DataFrame after removing 2nd & 4th rows:
   col1  col2  col3
0     1     4     7
1     4     5     8
3     4     7     0


23. . Write a Pandas program to convert DataFrame column type from string to datetime.

In [ ]:
import pandas as pd
string=['3/11/2000','3/12/2000','3/13/2000']
s=pd.Series(string)
print("Original:")
print(s)
news=pd.to_datetime(s)
print("\nOriginal DataFrame (string to datetime):")
print(news)

Original:
0    3/11/2000
1    3/12/2000
2    3/13/2000
dtype: object

Original DataFrame (string to datetime):
0   2000-03-11
1   2000-03-12
2   2000-03-13
dtype: datetime64[ns]


24.Write a Pandas program to find the row for where the value of a given column is maximum.

In [ ]:
import pandas as pd
data={"col1":[1,2,3,4,7],
      "col2":[4,5,6,9,5],
      "col3":[7,8,12,1,11]}
df=pd.DataFrame(data)
print("orginal dataframe:")
print(df)
print("\nRow where col1 has maximum value:")
print(df["col1"].argmax())
print("\nRow where col2 has maximum value:")
print(df["col2"].argmax())
print("\nRow where col3 has maximum value:")
print(df["col3"].argmax())

orginal dataframe:
   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6    12
3     4     9     1
4     7     5    11

Row where col1 has maximum value:
4

Row where col2 has maximum value:
3

Row where col3 has maximum value:
2


25. Write a Pandas program to get the datatypes of columns of a DataFrame.

In [ ]:
import pandas as pd
data = {'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'],
        'score': [12.5, 9, 16.5, "np.nan", 9, 20, 14.5, "np.nan", 8, 19]}
df=pd.DataFrame(data,index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
print("orginal dataframe:")
print(df)
print("\nData types of the columns of the said DataFrame:")
print(df.dtypes)

orginal dataframe:
   attempts       name qualify   score
a         1  Anastasia     yes    12.5
b         3       Dima      no       9
c         2  Katherine     yes    16.5
d         3      James      no  np.nan
e         2      Emily      no       9
f         3    Michael     yes      20
g         1    Matthew     yes    14.5
h         1      Laura      no  np.nan
i         2      Kevin      no       8
j         1      Jonas     yes      19

Data types of the columns of the said DataFrame:
attempts     int64
name        object
qualify     object
score       object
dtype: object


26. Write a Pandas program to group by the first column and get second column as lists in rows.

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'col1': ['C1', 'C1', 'C2', 'C2', 'C2', 'C3', 'C2'],
    'col2': [1, 2, 3, 3, 4, 6, 5]
})

print("Original DataFrame:")
print(df)

df = df.groupby('col1')['col2'].apply(list)

print("\nGroup on the 'col1':")
print(df)

Original DataFrame:
  col1  col2
0   C1     1
1   C1     2
2   C2     3
3   C2     3
4   C2     4
5   C3     6
6   C2     5

Group on the 'col1':
col1
C1          [1, 2]
C2    [3, 3, 4, 5]
C3             [6]
Name: col2, dtype: object


27 Write a Pandas program to count number of columns of a DataFrame.

In [ ]:
import pandas as pd
data={"col1":[1,2,3,4,7],
      "col2":[4,5,6,9,5],
      "col3":[7,8,12,1,11]}
df=pd.DataFrame(data)
print("orginal dataframe:")
print(df)
print("\nnumber of columns of a DataFrame:")
print(df.shape[1])

orginal dataframe:
   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6    12
3     4     9     1
4     7     5    11

number of columns of a DataFrame:
3


28. Write a Pandas program to get first n records of a DataFrame.

In [ ]:
import pandas as pd
data={"col1":[1,2,3,4,7,11],
      "col2":[4,5,6,9,5,0],
      "col3":[7,5,8,12,1,11]}
df=pd.DataFrame(data)
print("orginal DataFrame:")
print(df)
n=3
print("\n first 3 records of a DataFrame:")
print(df.head(n))

orginal DataFrame:
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

 first 3 records of a DataFrame:
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8


29. Write a Pandas program to get last n records of a DataFrame.

In [ ]:
import pandas as pd
data={"col1":[1,2,3,4,7,11],
      "col2":[4,5,6,9,5,0],
      "col3":[7,5,8,12,1,11]}
df=pd.DataFrame(data)
print("orginal DataFrame:")
print(df)
n=3
print("\n last 3 records of a DataFrame:")
print(df.tail(n))

orginal DataFrame:
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

 last 3 records of a DataFrame:
   col1  col2  col3
3     4     9    12
4     7     5     1
5    11     0    11


30. Write a Pandas program to get topmost n records within each group of a DataFrame.

In [ ]:
import pandas as pd
data={"col1":[1,2,3,4,7,11],
      "col2":[4,5,6,9,5,0],
      "col3":[7,5,8,12,1,11]}
df=pd.DataFrame(data)
print("orginal DataFrame:")
print(df)
print("\ntopmost n records within each group of a DataFrame:")
df1=df.nlargest(3,"col1")
print(df1)
df2=df.nlargest(3,"col2")
print(df2)
df3=df.nlargest(3,"col3")
print(df3)

orginal DataFrame:
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

topmost n records within each group of a DataFrame:
   col1  col2  col3
5    11     0    11
4     7     5     1
3     4     9    12
   col1  col2  col3
3     4     9    12
2     3     6     8
1     2     5     5
   col1  col2  col3
3     4     9    12
5    11     0    11
2     3     6     8


31. Write a Pandas program to add a prefix or suffix to all columns of a given DataFrame.

In [ ]:
import pandas as pd
data={'w':[68,75,86,80,66],
      'x':[78,85,96,80,86],
      'y':[84,94,89,83,86],
      'z':[86,97,96,72,83]}
df=pd.DataFrame(data)
print(df)
print("\nAdd a prefix to all columns of a given DataFrame.")
df1=df.add_prefix("A_")
print(df1)
print("\nAdd a suffix to all columns of a given DataFrame.")
df2=df.add_suffix("_1")
print(df2)

    w   x   y   z
0  68  78  84  86
1  75  85  94  97
2  86  96  89  96
3  80  80  83  72
4  66  86  86  83

Add a prefix to all columns of a given DataFrame.
   A_w  A_x  A_y  A_z
0   68   78   84   86
1   75   85   94   97
2   86   96   89   96
3   80   80   83   72
4   66   86   86   83

Add a suffix to all columns of a given DataFrame.
   w_1  x_1  y_1  z_1
0   68   78   84   86
1   75   85   94   97
2   86   96   89   96
3   80   80   83   72
4   66   86   86   83


32. Write a Pandas program to convert continuous values of a column in a given DataFrame to categorical.

In [ ]:
import pandas as pd
df = pd.DataFrame({
    'name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Syed Wharton', 'Kierra Gentry'],
      'age': [18, 22, 85, 50, 80, 5]})
print("Original DataFrame:")
print(df)
print('\nAge group:')
df["age_groups"] = pd.cut(df["age"], bins = [0, 18, 65, 99], labels = ["kids", "adult", "elderly"])
print(df["age_groups"])

Original DataFrame:
             name  age
0  Alberto Franco   18
1    Gino Mcneill   22
2     Ryan Parkes   85
3    Eesha Hinton   50
4    Syed Wharton   80
5   Kierra Gentry    5

Age group:
0       kids
1      adult
2    elderly
3      adult
4    elderly
5       kids
Name: age_groups, dtype: category
Categories (3, object): ['kids' < 'adult' < 'elderly']


33. Write a Pandas program to append rows to an existing DataFrame and display the combined data.

In [ ]:
import pandas as pd
student_data={'student_id':['s1','s2','s3','s4','s5'],
              'name':['Danniella Fenton','Ryder Storey','Bryce Jensen',' Ed Bernal','Kwame Morin'],
              'marks':[200,210,190,222,199]}
df=pd.DataFrame(student_data)
print(df)
print("\nNew Row:")
s6=pd.Series(['S6', 'Scarlette Fisher', 205],index=['student_id', 'name', 'marks'])
print(s6)
print("\ncombined data:")
ndata=df.append(s6, ignore_index = True)
print(ndata)

  student_id              name  marks
0         s1  Danniella Fenton    200
1         s2      Ryder Storey    210
2         s3      Bryce Jensen    190
3         s4         Ed Bernal    222
4         s5       Kwame Morin    199

New Row:
student_id                  S6
name          Scarlette Fisher
marks                      205
dtype: object

combined data:
  student_id              name  marks
0         s1  Danniella Fenton    200
1         s2      Ryder Storey    210
2         s3      Bryce Jensen    190
3         s4         Ed Bernal    222
4         s5       Kwame Morin    199
5         S6  Scarlette Fisher    205


<ipython-input-25-976977c95146>:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ndata=df.append(s6, ignore_index = True)


34 Write a Pandas program to join the two given dataframes along rows and merge with another dataframe along the common column id.

In [ ]:
import pandas as pd
student_data1 = pd.DataFrame({
        'student_id': ['S1', 'S2', 'S3', 'S4', 'S5'],
         'name': ['Danniella Fenton', 'Ryder Storey', 'Bryce Jensen', 'Ed Bernal', 'Kwame Morin'],
        'marks': [200, 210, 190, 222, 199]})

student_data2 = pd.DataFrame({
        'student_id': ['S4', 'S5', 'S6', 'S7', 'S8'],
        'name': ['Scarlette Fisher', 'Carla Williamson', 'Dante Morse', 'Kaiser William', 'Madeeha Preston'],
        'marks': [201, 200, 198, 219, 201]})

exam_data = pd.DataFrame({
        'student_id': ['S1', 'S2', 'S3', 'S4', 'S5', 'S7', 'S8', 'S9', 'S10', 'S11', 'S12', 'S13'],
        'exam_id': [23, 45, 12, 67, 21, 55, 33, 14, 56, 83, 88, 12]})

print("\nJoin first two said dataframes along rows:")
result_data = pd.concat([student_data1, student_data2])
print(result_data)

print("\nNow join the said result_data and df_exam_data along student_id:")
final_merged_data = pd.merge(result_data, exam_data, on='student_id')
print(final_merged_data)



Join first two said dataframes along rows:
  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199
0         S4  Scarlette Fisher    201
1         S5  Carla Williamson    200
2         S6       Dante Morse    198
3         S7    Kaiser William    219
4         S8   Madeeha Preston    201

Now join the said result_data and df_exam_data along student_id:
  student_id              name  marks  exam_id
0         S1  Danniella Fenton    200       23
1         S2      Ryder Storey    210       45
2         S3      Bryce Jensen    190       12
3         S4         Ed Bernal    222       67
4         S4  Scarlette Fisher    201       67
5         S5       Kwame Morin    199       21
6         S5  Carla Williamson    200       21
7         S7    Kaiser William    219       55
8         S8   Madeeha Preston    201       33
